export type EvolutionParameterKind = "none" | "number" | "item" | "move" | "pokemon" | "type";

// Confirmed from PBEvolution::EVONAMES and EVOPARAM in Pokemon_Evolution.
export const EVOLUTION_PARAMETER_KINDS = {
  Happiness: "none",
  HappinessDay: "none",
  HappinessNight: "none",
  Level: "number",
  Trade: "none",
  TradeItem: "item",
  Item: "item",
  AttackGreater: "number",
  AtkDefEqual: "number",
  DefenseGreater: "number",
  Silcoon: "number",
  Cascoon: "number",
  Ninjask: "number",
  Shedinja: "number",
  Beauty: "number",
  ItemMale: "item",
  ItemFemale: "item",
  DayHoldItem: "item",
  NightHoldItem: "item",
  HasMove: "move",
  HasInParty: "pokemon",
  LevelMale: "number",
  LevelFemale: "number",
  Location: "number",
  TradeSpecies: "pokemon",
  LevelDay: "number",
  LevelNight: "number",
  LevelDarkInParty: "number",
  LevelRain: "number",
  HappinessMoveType: "type",
  Custom1: "number",
  Custom2: "number",
  Custom3: "number",
  Custom4: "number",
  Custom5: "number",
} as const satisfies Readonly<Record<string, EvolutionParameterKind>>;
