import type { BattleMove } from "./types.js";

export const MINIMAL_MOVE_CATALOG = {
  TACKLE: { id: 303, internalName: "TACKLE", name: "Charge", functionCode: "000", power: 40, type: "NORMAL", category: "Physical", accuracy: 100, pp: 35, priority: 0, effectChance: 0 },
  QUICKATTACK: { id: 310, internalName: "QUICKATTACK", name: "Vive-Attaque", functionCode: "000", power: 40, type: "NORMAL", category: "Physical", accuracy: 100, pp: 30, priority: 1, effectChance: 0 },
  SCRATCH: { id: 311, internalName: "SCRATCH", name: "Griffe", functionCode: "000", power: 40, type: "NORMAL", category: "Physical", accuracy: 100, pp: 35, priority: 0, effectChance: 0 },
  WATERGUN: { id: 551, internalName: "WATERGUN", name: "Pistolet à O", functionCode: "000", power: 45, type: "WATER", category: "Special", accuracy: 100, pp: 25, priority: 0, effectChance: 0 },
  VINEWHIP: { id: 208, internalName: "VINEWHIP", name: "Fouet Lianes", functionCode: "000", power: 45, type: "GRASS", category: "Physical", accuracy: 100, pp: 15, priority: 0, effectChance: 0 },
  SWIFT: { id: 299, internalName: "SWIFT", name: "Météores", functionCode: "0A5", power: 60, type: "NORMAL", category: "Special", accuracy: 0, pp: 20, priority: 0, effectChance: 0 },
  SLEEPPOWDER: { id: 218, internalName: "SLEEPPOWDER", name: "Poudre Dodo", functionCode: "003", power: 0, type: "GRASS", category: "Status", accuracy: 75, pp: 15, priority: 0, effectChance: 0 },
  POISONPOWDER: { id: 445, internalName: "POISONPOWDER", name: "Poudre Toxik", functionCode: "005", power: 0, type: "POISON", category: "Status", accuracy: 75, pp: 35, priority: 0, effectChance: 0 },
  TOXIC: { id: 446, internalName: "TOXIC", name: "Toxik", functionCode: "006", power: 0, type: "POISON", category: "Status", accuracy: 90, pp: 10, priority: 0, effectChance: 0 },
  THUNDERWAVE: { id: 83, internalName: "THUNDERWAVE", name: "Cage-Éclair", functionCode: "007", power: 0, type: "ELECTRIC", category: "Status", accuracy: 90, pp: 20, priority: 0, effectChance: 0 },
  WILLOWISP: { id: 151, internalName: "WILLOWISP", name: "Feu Follet", functionCode: "00A", power: 0, type: "FIRE", category: "Status", accuracy: 85, pp: 15, priority: 0, effectChance: 0 },
  ICEBEAM: { id: 243, internalName: "ICEBEAM", name: "Laser Glace", functionCode: "00C", power: 90, type: "ICE", category: "Special", accuracy: 100, pp: 10, priority: 0, effectChance: 10 },
  LUZDECADENTE: { id: 652, internalName: "LUZDECADENTE", name: "Lumière Décadente", functionCode: "159", power: 50, type: "FAIRY", category: "Special", accuracy: 100, pp: 20, priority: 0, effectChance: 100 },
  CUT: { id: 301, internalName: "CUT", name: "Coupe", functionCode: "906", power: 60, type: "NORMAL", category: "Physical", accuracy: 95, pp: 30, priority: 0, effectChance: 70 },
  HOWL: { id: 373, internalName: "HOWL", name: "Grondement", functionCode: "01C", power: 0, type: "NORMAL", category: "Status", accuracy: 0, pp: 40, priority: 0, effectChance: 0 },
  HARDEN: { id: 370, internalName: "HARDEN", name: "Armure", functionCode: "01D", power: 0, type: "NORMAL", category: "Status", accuracy: 0, pp: 30, priority: 0, effectChance: 0 },
  FLAMECHARGE: { id: 145, internalName: "FLAMECHARGE", name: "Nitrocharge", functionCode: "01F", power: 50, type: "FIRE", category: "Physical", accuracy: 100, pp: 20, priority: 0, effectChance: 100 },
  CHARGEBEAM: { id: 78, internalName: "CHARGEBEAM", name: "Rayon Chargé", functionCode: "020", power: 50, type: "ELECTRIC", category: "Special", accuracy: 90, pp: 10, priority: 0, effectChance: 70 },
  GROWL: { id: 368, internalName: "GROWL", name: "Rugissement", functionCode: "042", power: 0, type: "NORMAL", category: "Status", accuracy: 100, pp: 40, priority: 0, effectChance: 0 },
  TAILWHIP: { id: 419, internalName: "TAILWHIP", name: "Mimi-Queue", functionCode: "043", power: 0, type: "NORMAL", category: "Status", accuracy: 100, pp: 30, priority: 0, effectChance: 0 },
  ICYWIND: { id: 250, internalName: "ICYWIND", name: "Vent Glace", functionCode: "044", power: 55, type: "ICE", category: "Special", accuracy: 95, pp: 15, priority: 0, effectChance: 100 },
  SNARL: { id: 30, internalName: "SNARL", name: "Aboiement", functionCode: "045", power: 55, type: "DARK", category: "Special", accuracy: 95, pp: 15, priority: 0, effectChance: 100 },
  SHADOWBALL: { id: 175, internalName: "SHADOWBALL", name: "Ball'Ombre", functionCode: "046", power: 80, type: "GHOST", category: "Special", accuracy: 100, pp: 15, priority: 0, effectChance: 20 },
  SANDATTACK: { id: 238, internalName: "SANDATTACK", name: "Jet de Sable", functionCode: "047", power: 0, type: "GROUND", category: "Status", accuracy: 100, pp: 15, priority: 0, effectChance: 0 },
} as const satisfies Readonly<Record<string, BattleMove>>;
